### ISSUE TITLE
Max exclude parameters too low?

### ISSUE THREAD

**Issue by coderesting** [jeff-saupe/ScheduleCleaner#43]
I just got an email where someone wanted to filter out 19 compulsory modules. Since the max number is currently 10 we should probably increase this limit here:
https://github.com/jeff-saupe/ScheduleCleaner/blob/da32d600eb101ee4471ccfe84a45cef910f4689f/src/main/java/de/saupe/jeff/schedulecleaner/fixes/impl/ExcludeEvent.java#L12

What do you think @jeff-saupe?

**Comment by jeff-saupe** [comment]
I've never thought someone would need more than 10 exclusions, but sure we can set it to 99 or something like that. 😂👍🏼

**Comment by coderesting** [comment]
Nice. I'll make a PR.

**Comment by jeff-saupe** [comment]
This has been reversed with commit #51. It was against the initial idea behind multiple exclusions. For clarification:

Multiple exclusions should **each** be created with the start of "&exclude=" in the URL. This means the parameters of "&exclude=" **do not** represent multiple exclusions, but they represent the phrases an event must **all** contain to be excluded. Take a look at this example configuration:


<details>
<summary>Click here</summary>

![Example](https://github.com/jeff-saupe/ScheduleCleaner/blob/dev/meta/example.jpg?raw=true)

**URL:**
https://schedule-cleaner.herokuapp.com/cleaned-schedule/A18a_6.ics?exclude=Englisch%3BMcCabe-Boeck&exclude=Agility&exclude=International+Relations&exclude=Applications+in+Data+Science&replace=Allgemeine+Volkswirtschaftslehre%3BVWL&title=keepCode&location
</details>

The best example for this way of implementation is the English course. If you'd only use **Englisch** as a parameter, the second English course would be removed as well. Sure, you could use the teacher instead of Englisch as a parameter, but you can't be sure that you don't have this teacher in another course/module.
